responses = {
    "happy": ["That's wonderful to hear! What made you feel this way?",
              "I'm glad you're feeling good. Tell me more about it.",
              "Sounds like something great happened! I'd love to hear more.",
              "I'm happy for you! Can you share what's been going well?",
              "That's exciting! How did that make you feel?"],

    "sad": [
        "I hear you. Do you want to tell me more about what's bothering you?",
        "I'm here to listen. What's been weighing on you?",
        "It's okay to feel this way. Can you share what happened?",
        "I understand. Tell me more about how you're feeling.",
        "That sounds tough. What's on your mind right now?",
    ],

    "stress": [
        "It sounds like a lot is going on. Can you tell me more?",
        "I understand this is stressful. What's been happening?",
        "Take your time—what's on your mind right now?",
        "That seems overwhelming. Want to talk about it?",
        "I'm listening. Can you share what's causing this stress?",
    ],

    "angry": [
        "I hear that you're upset. Can you tell me more about it?",
        "It's okay to feel angry. What's happening that makes you feel this way?",
        "I understand your frustration. Can you share more details?",
        "I'm here to listen. What's on your mind right now?",
        "That sounds irritating. Want to vent about it?",
    ]
}

happy_keywords = ["happy", "joy", "fortunate", "good",
                  "lucky",
                  "favourable",
                  "advantageous",
                  "opportune",
                  "timely",
                  "well timed",
                  "convenient",
                  "propitious",
                  "felicitous",
                  "auspicious",
                  "better",
                  ]
sad_keywords = ["sad",
                "unhappy",
                "sorrowful",
                "dejected",
                "regretful",
                "depressed",
                "downcast",
                "miserable",
                "downhearted",
                "down",
                "despondent",
                "despairing",
                ]
stress_keywords = ["stress",
                   "pressure",
                   "tension",
                   "strain",
                   "tightness",
                   "tautness",
                   "tensity",
                   "strain",
                   "pressure",
                   "tension",
                   "nervous tension",
                   "worry",
                   "anxiety",
                   ]
angry_keywords = ["angry",
                  "irate",
                  "annoyed",
                  "cross",
                  "vexed",
                  "irritated",
                  "exasperated",
                  "indignant",
                  "aggrieved",
                  "irked",
                  "piqued",
                  "displeased",
                  "provoked",
                  ]
